name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Critical!
          publish_dir: ./build  # or your build folder
